#!/bin/sh

# Use neovim for vim if present.
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"

# Verbosity and settings that you pretty much just always are going to want.
alias \
	bat="cat /sys/class/power_supply/BAT?/capacity" \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -v" \
	mkd="mkdir -pv" \
	yt="youtube-dl --add-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	nmap="grc nmap"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	trem="transmission-remote" \
	YT="youtube-viewer" \
	sdn="sudo shutdown -h now" \
	f="$FILE" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="sudo pacman" \
	xi="sudo xbps-install" \
	xr="sudo xbps-remove -R" \
	xq="xbps-query" \
	bt="bluetoothctl" \
	wifi="sudo wpa_supplicant -iwlp1s0 -c /etc/wpa_supplicant/wpa_supplicant.conf -B" \
	dhcp="sudo dhcpcd wlp1s0" \
	pvpn="sudo protonvpn" \
	pdflatex="pdflatex -shell-escape -interactions=nonstopmode" \
	xclip="xclip -sel clip <" \

# Directories for uni
alias \
	adrm="cd /home/nicola/HSLU/4_Semester/ADRM" \
	anls="cd /home/nicola/HSLU/4_Semester/ANLS" \
	itre="cd /home/nicola/HSLU/4_Semester/ITRE" \
	krypto="cd /home/nicola/HSLU/4_Semester/KRYPTO" \
	netda="cd /home/nicola/HSLU/4_Semester/NETDA" \
	spren2="cd /home/nicola/HSLU/4_Semester/SPREN2" \

# This alias is important. It enables the `pauseallmpv` command.
alias mpv="mpv --input-ipc-server=/tmp/mpvsoc$(date +%s)"

# Some other stuff
alias \
	magit="nvim -c MagitOnly" \
	ref="shortcuts >/dev/null; source ~/.config/shortcutrc" \
	weath="less -S ~/.local/share/weatherreport" \
